---
- name: Install Packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  register: apt_status
  until: apt_status is success
  delay: 10
  retries: 3

- name: Install Python Packages
  pip:
    name: "{{ python_packages }}"
    executable: pip3

- name: Remove Python Packages
  pip:
    name: "{{ python_packages_remove }}"
    executable: pip3
    state: absent

- name: Make sure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
