---
packages:
  - apt-transport-https
  - byobu
  - ca-certificates
  - curl
  - dnsutils
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - containerd.io
  - gnupg
  - htop
  - lsb-release
  - ncdu
  - net-tools
  - python3
  - python3-pip
  - reptyr
  - screen
  - software-properties-common
  - tree
  - unzip
  - neovim
  - zip
  - zsh

python_packages:
  - docker
  - jsondiff
  - pyyaml

python_packages_remove:
  - docker-py
