---
- name: Disallow root SSH Access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^.?PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
    state: present
    backrefs: yes
  notify: Restart sshd

- name: Disallow Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^.?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    backrefs: yes
  notify: Restart sshd

- name: "Add Authorized Keys for admin Account"
  authorized_key:
    user: "{{ admin.user }}"
    state: present
    key: "{{ lookup('file', '../../../../keys/' + item + '.pub') }}"
    exclusive: false
  with_items:
    - 'id_ed_me_2022'
