- name: Check if directory exists
  stat:
    path: "{{ dir.path }}"
  register: directory

- name: Notify if the directory already existed
  debug:
    msg: "{{ dir.path }} is already existed"
  when: directory.stat.exists

- name: Create the directory if does not exist
  file:
    path: "{{ dir.path }}"
    state: directory
    owner: "{{ dir.user }}"
    group: "{{ dir.group }}"
    mode: "{{ dir.mode }}"
  when: directory.stat.exists == false
